language: php

dist: trusty

sudo: required

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - hhvm

cache:
  directories:
    - $HOME/.composer/cache

install:
  # Install shellcheck
  - sudo ./test/build/install.sh

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

script:
  # Lint shell
  - ./test/build/build.sh
  # Install webstatus
  - sudo ./bin/install.sh -y
