language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - hhvm

install:
  # Install shellcheck
  - sudo ./test/build/install.sh
  # Install webstatus
  - sudo ./bin/install.sh -y

script:
  - ./test/build/build.sh
